_BASE_: ../Base-SBS.yml

MODEL:
  BACKBONE:
    DEPTH: 101x
    WITH_IBN: True
  WEIGHTS: 'fast_reid/demo/msmt_sbs_R101-ibn.pth'

DATASETS:
  NAMES: ("MSMT17",)
  TESTS: ("MSMT17",)

OUTPUT_DIR: logs/msmt17/sbs_R101-ibn
